export const POKEMON_LIST_LOADING = 'POKEMON_LIST_LOADING'
export const POKEMON_LIST_SUCCESS = 'POKEMON_LIST_SUCCESS'
export const POKEMON_LIST_FAIL = 'POKEMON_LIST_FAIL'

export const POKEMON_MULTIPLE_LOADING = 'POKEMON_MULTIPLE_LOADING'
export const POKEMON_MULTIPLE_SUCCESS = 'POKEMON_MULTIPLE_SUCCESS'
export const POKEMON_MULTIPLE_FAIL = 'POKEMON_MULTIPLE_FAIL'

export const POKEMON_SEARCH_LOADING = 'POKEMON_SEARCH_LOADING'
export const POKEMON_SEARCH_SUCCESS = 'POKEMON_SEARCH_SUCCESS'
export const POKEMON_SEARCH_FAIL = 'POKEMON_SEARCH_FAIL'

export const CAUGHT_POKEMON_SUCCESS = 'CAUGHT_POKEMON_SUCCESS'
export const CAUGHT_POKEMON_FAIL = 'CAUGHT_POKEMON_FAIL'

export const CAUGHT_LIST_LOADING = 'CAUGHT_LIST_LOADING'
export const CAUGHT_LIST_SUCCESS = 'CAUGHT_LIST_SUCCESS'
export const CAUGHT_LIST_FAIL = 'CAUGHT_LIST_FAIL'